export const GET_REGIONS = 'GET_REGIONS';
export const SET_LOADING = 'SET_LOADING';
export const REGIONS_ERROR = 'REGIONS_ERROR';

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const COUNTRIES_ERROR = 'COUNTRIES_ERROR';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';
export const GET_CURRENT_DATA = 'GET_CURRENT_DATA';
export const GET_GLOBAL_DATA = 'GET_GLOBAL_DATA';
export const CLEAR_CURRENT_DATA = 'CLEAR_CURRENT_DATA';
export const CLEAR_GLOBAL_DATA = 'CLEAR_GLOBAL_DATA';